[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "scikit-build",
  "cmake>=3.15",
  "pybind11>=2.3",
  "ninja; platform_system!='Windows'",
  "numpy>=1.20.3",
  "scipy>=1.7.1",
  "psutil>=5.8.0",
]
build-backend = "setuptools.build_meta"
