name: C++ build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build C++
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest] #, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure GraphInf CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON

    - name: Build GraphInf
      run: cmake --build ${{github.workspace}}/build
    
    - name: Unit tests
      working-directory: ${{github.workspace}}/build
      run: |
        ./${{github.workspace}}/build/test/test_generator
        ./${{github.workspace}}/build/test/test_utility
        ./${{github.workspace}}/build/test/test_proposers
        ./${{github.workspace}}/build/test/test_priors
        ./${{github.workspace}}/build/test/test_graph
        ./${{github.workspace}}/build/test/test_data