name: C++ build
on:
  push:
    branches: [ main, fix-workflow ]
  pull_request:
    branches: [ main, fix-workflow ]

jobs:
  build:
    name: Build C++
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure GraphInf CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON

    - name: Build GraphInf
      run: cmake --build ${{github.workspace}}/build
    
    - name: Unit tests
      working-directory: ${{github.workspace}}/build
      run: ctest ${{github.workspace}}/build --output-on-failure