name: C++ tests

on:
    - push
    - pull_request

jobs:
    cpp-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Loading submodules
              shell: bash
              run: |
                    git submodule init
                    git submodule update

            - name: Install C++ dependencies
              shell: bash
              run: |
                    sudo apt install gcc-9 g++ cmake

            - name: Running graphinf C++ test
              shell: bash
              run: |
                    echo Running C++ tests
                    cmake -S . -B build -DBUILD_TESTS=ON
                    cmake --build build -j8
                    ctest build/tests