name: Python interface

on:
    - push
    - pull_request

jobs:
    python-interface:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                    python-version: 3.9

            - name: Install C++ dependencies
              shell: bash
              run: |
                    sudo apt install gcc-9 g++ cmake
                    pip install --upgrade pip

            - name: Installing basegraph
              shell: bash
              run: |
                    echo Installing basegraph
                    pip install ./ext/basegraph

            - name: Installing SamplableSet==2.2.0
              shell: bash
              run: |
                    echo Installing SamplableSet
                    pip install ./ext/SamplableSet

            - name: Installing graphinf
              shell: bash
              run: |
                    echo Installing graphinf
                    pip install . -v

            - name: Run tests
              shell: bash
              run: pytest ./tests
