name: Python interface

on:
    - push
    - pull_request

jobs:
    python-interface:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                    python-version: 3.9

            - name: Loading submodules
              shell: bash
              run: |
                    git submodule init
                    git submodule update

            - name: Install C++ dependencies
              shell: bash
              run: |
                    sudo apt install gcc-9 g++ cmake
                    pip install --upgrade pip

            - name: Installing basegraph==1.0.0
              shell: bash
              run: |
                    cd graphinf_cpp/base_graph
                    [ ! -d "./build" ] && mkdir build
                    cd build
                    cmake ..
                    make -j4
                    cd ..
                    pip install .

            - name: Installing SamplableSet==2.2.0
              shell: bash
              run: |
                    echo Installing SamplableSet==2.2.0
                    cd graphinf_cpp/SamplableSet/src
                    [ ! -d "./build" ] && mkdir build
                    cd build
                    cmake ..
                    make -j4
                    cd ../..
                    pip install .

            - name: Building graphinf backend and run c++ tests
              shell: bash
              run: |
                    echo Build backend and tests
                    cd graphinf_cpp
                    [ ! -d "./build" ] && mkdir build
                    cd build
                    cmake ..
                    make -j4
                    ctest -C Debug --output-on-failure --verbose

            - name: Installing dev-dependencies
              shell: bash
              run: |
                    pip install -r requirements_dev.txt
                    pip install -r requirements.txt
                    pip install pybind11

            - name: Installing graphinf==0.0.1
              shell: bash
              run: |
                    [ -d "./build" ] && rm -r build
                    pip install .[testing]

            # - name: Run tests
            #   shell: bash
            #   run: pytest ./tests
